spring:
  profiles:
    active: default
  cloud:
    config:
      enabled: true
      server:
        git:
          default-label: main
          uri: https://github.com/AdrianNMS/config_file
          #search-paths: data
  application:
    name: config-service
